import { createTheme } from '@react-universal/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppRouterProdivder } from '@react-universal/next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <AppRouterProdivder
          theme={createTheme({
            fonts: {
              body: {
                family: inter.style.fontFamily,
              } as any,
              heading: {
                family: inter.style.fontFamily,
              } as any,
            },
          })}
        >
          {children}
        </AppRouterProdivder>
      </body>
    </html>
  );
}
