import { AppRouterProdivder } from '@react-universal/next';
import type { Metadata } from 'next';
import { config, font } from '../universal.config';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={font.className}>
        <AppRouterProdivder theme={config.theme}>{children}</AppRouterProdivder>
      </body>
    </html>
  );
}
